# Generated by Django 2.2.7 on 2020-04-15 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter application name', max_length=30)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
